@startuml
title 図4-16 画面・帳票ダイアグラム
object 商品登録画面 <<画面>> {
    - 商品名
    - 取引先
    - 荷姿
    - 発注単位
    - 商品カテゴリ
}
object 販売状況照会 <<画面>> {
    - 月
    - 商品カテゴリ
}
商品登録画面 -[hidden]-- 販売状況照会
object 商品売上詳細 {
    - 商品
    - 売上数量
    - 売上金額
}
販売状況照会 *-right- 商品売上詳細
object 発注登録 <<画面>> {
    - 商品
    - 発注日
    - 発注数量
    - 入荷予定日
}
販売状況照会 -[hidden]- 発注登録
object 商品説明 <<画面>> {
    - 商品カテゴリ
    - 商品名
    - 商品説明
    - 価格
}
商品登録画面 -[hidden]right---- 商品説明
object 詳細説明 {
    - 商品説明
}
商品説明 *-right- 詳細説明
object カート処理 <<画面>> {
    - 受注番号
}
object カート内商品 {
    - 商品
    - 数量
}
商品説明 -[hidden]- カート処理
カート処理 *-right- カート内商品
object 決済処理 <<画面>> {
    - 顧客名
    - 住所
    - 決済方法
}
カート処理 -[hidden]- 決済処理
object 受注照会 <<画面>> {
    - 顧客名
    - 受注日
    - 状態
}
決済処理 -[hidden]- 受注照会
object 受注商品 {
    - 商品
    - 受注数
}
受注照会 *-right- 受注商品
object オーダー取り消し {
    - 受注番号
}
受注照会 -[hidden]- オーダー取り消し
@enduml