@startuml
title 図4-21 データ構造に起因するビジネスルール
object 入金情報 {
    - 入金日
    - 入金者名
    - 金額
}
note left: 入金は分割はなく一括払いとする
object オーダー情報 {
    - オーダーID
    - オーダー日
    - 決済方法
}
object 出荷指示情報 {
    - 入荷予定日
    - 入荷待ちの有無
}
object 送り先情報 {
    - 送り先名
    - 郵便番号
    - 住所
    - 電話番号
}
note right: 商品の送り先は1箇所のみ
object オーダー商品 {
    - 数量
}
note right: 一回のオーダーで複数商品のオーダーが可能
note right: 出荷は分納はなく1回で済ませる
オーダー情報 --"0..1" 入金情報
オーダー情報 "1"--"1" 出荷指示情報
オーダー情報 "1"--"1" 出荷情報
オーダー情報 "1" o--"1" 送り先情報
出荷情報 ..> 出荷指示情報
出荷情報 "1" ..> 送り先情報
出荷情報 ..> オーダー商品
オーダー商品 "*" --* オーダー情報
@enduml