@startuml
title 図4-23 プロトコルダイアグラム
|オーダー商品の出荷|
    start
    :出荷待ち;
    :出荷指示/出荷指示通知}
    note right: イベント「出荷指示」で\n「出荷指示通知」機能が呼ばれる
    :出荷指示受付済み;
    :出棺完了通知/出荷完了記録}
    note right: イベント「出荷完了通知」で\n「出荷完了記録」機能が呼ばれる
    :出荷完了;
    stop
|オーダー商品の入金|
    start
    repeat
    repeat while (入金待ち) is (入金額!=購入金額) not (入金額==購入金額)
    :入金通知[入金額==購入金額]/入金登録}
    note right: イベント「入金通知」で\n「入金登録」機能が呼ばれる
    :入金確認済み;
    stop
@enduml