@startuml
title 図4-28 商品に関わるビジネスルール
state 販売対象外商品
state 販売対象商品 {
    state 在庫なし {
        state 追加発注中
    }
     state 在庫あり {
        state 追加発注なし
        state "追加発注中" as S2
     }
}
[*] --> 追加発注中: 商品を発注する
販売対象外商品 -right-> 追加発注中: 商品を発注する
追加発注中 --> 追加発注なし: 入荷通知
追加発注中 <-- 在庫あり: 在庫切れ
追加発注なし -right-> S2: 商品を発注する
追加発注なし <-right- S2: 入荷通知
販売対象外商品 <-right- 在庫あり: 在庫切れ\n[追加発注禁止]
販売対象外商品 --> [*]
@enduml