@startuml
title 図5-3 要望を洗い出す
actor 作業者 as A1
actor アナリスト as A2
actor プロジェクトリーダー as A3
actor 担当者 as A4
note "要求をレビューするための\nポイントを示して欲しい" as N1
note "各ダイアグラム毎に\n状況を把握したい" as N2
note "モデルの整合性を\nチェックしたい" as N3
note "要件定義のための\n各ダイアグラムの役割を\nすぐに参照できるようにして欲しい" as N4
A1 <|--- A2
A1 <|-- A3
A1 <|--- A4
A3 .right. N1
N1 .right. A2
A3 .down. N2
A2 .down. N3
A4 .down. N4
@enduml