@startuml
title 図5-4 機能要求を洗い出す
note "要件定義の\n全体構造が分かること" as N5
note "要件定義のための\n各ダイアグラムの役割を\nすぐに参照できること" as N6
note "要件定義で満たしておく\nべきことが示されること" as N7
note "定義しているモデル間の\n関係にもとずいてモデルの\n整合性をチェックできること" as N8
note "チェックした結果の\n評価方法を示すこと" as N9
note "各々のモデルの種類毎に\n全体を表す一覧情報を用意し、\nどこまでが出来ているか\n分かるようにすること" as N10
N5 .. N6
N5 .. N7
N10 -[hidden]- N8
N8 .. N9
@enduml