@startuml
title 図5-7 作業用の利用シーンダイアグラム
note as N1
    ＜各ダイアグラムの作成方法を知る＞
    作成者はこのシステムの利用者全般を指します。
    このシステムの利用者は作成するダイアグラムの目的や役割に関心があります。
    作業者はモデルチェックの時にもシステムを使って各ダイアグラム説明を参照し
    たいと考えています。
    また、そのダイアグラムと他のダイアグラムとの関係を知り、ダイアグラム内の各
    情報の粒度などを確認します。
    作成したダイアグラムを参照するとそのダイアグラムの説明が連動して表示され
    るので、その説明を読みながら作成したダイアグラムの内容を確認します。
    ダイアグラム一覧でその全体像を知り、個々のダイアグラムを選択し、その
    ダイアグラム内の情報を参照します。各情報には関係する情報が表示(業務に関わる
    ユースケースなど)されるのでその関係を意識しながら、元になっているUMLツールの
    ダイアグラムを確認します
end note
note as N2
    ＜要件の整合性を確認する＞
    アナリストは要件についての最終責任を負うのでモデルの
    品質に関心があります。
    アナリストは毎日各担当者が定義したモデルの整合性を
    このシステムを使って確認します。
    各ダイアグラム毎にその中の情報(アクター、ユースケース、
    画面など)の関係を確認し整合性をチェックします。
    もし関係が定義されていない場合は担当者に連絡して翌日
    までに修正してもらいます。
end note
note as N3
    ＜自分の作業範囲と全体の作業の状況を確認する＞
    担当者は自分の割り当てられたモデルの品質に
    関心があります。
    自分に割り当てられているモデルをUMLツール上で
    作成し、1日何度かこのシステムを使って整合性の
    確認を行います。不備があればそこを直し提出します。
    また、全体としてどこまで進んでいるかをこのシステム
    を使って確認します
end note
actor 作業者 as A1
actor アナリスト as A2
actor 担当者 as A3
N1 .right. A1
A1 <|-- A2
A2 .. N2
A1 <|-- A3
A3 .. N3
@enduml