@startuml
title 図5-8 管理用の利用シーン
actor プロジェクトリーダー as A1
actor アナリスト as A2
note as N1
    ＜進捗確認＞
    プロジェクトリーダーは進捗に関心があります。そして成果物の品質を
    考慮して進捗を管理したいと考えています。
    プロジェクトリーダーは自分が管理しているプロジェクトの状況を
    日々管理するためにこのシステムを立ち上げて進捗を把握しています。
    進捗の把握は2つの視点から行っています。
    一つは必要なダイアグラムが洗い出されているか。もう一つが
    各ダイアグラムの洗練度合いを把握することです。
    画面の味方はダイアグラム別説明ですぐ分かるようになっているので、
    それを見ながら各ダイアグラムの完成度を把握します。そしてその結果
    で進捗を管理します。
end note
note as N2
    ＜要件をレビューする＞
    ダイアグラムナビゲーションで各ダイアグラムの目的を把握し、
    作成したモデルがその目的を満たしているかをレビューします。
    検証ナビゲーションで各ダイアグラムの関係性を把握し、
    要件定義として何処をチェックするかを知ります。
    レビュー参加者全員で上記の確認を行いその視点で各モデルを
    レビューします。
    各ダイアグラムの意味はダイアグラム説明を参照して確認します。
end note
note as N3
    ＜各ダイアグラムの精度を管理する＞
    業務フローやユースケースなどのダイアグラムの一覧を参照し、
    ダイアグラムの出来具合を見ながら、
    各ダイアグラムの精度を確認します。
end note
A1 .right. N1
A1 .right. N2
A1 .right. N3
A2 .right. N2
A2 .right. N3
N1 -[hidden]down- N2
N2 -[hidden]down- N3
@enduml