@startuml
title 図5-14 画面のラフスケッチ
rectangle 要件モデルチェック {
    rectangle Open
    rectangle 情報提供 {
        rectangle インデックス
        rectangle 説明
    }
    rectangle ダイアグラム表示 {
        rectangle ダイアグラム一覧
        rectangle ダイアグラムイメージ
        rectangle ダイアグラム内要素
    }
    Open -[hidden]- 情報提供
    情報提供 -[hidden]- ダイアグラム表示
}
note as N1
    ＜情報提供画面＞
    下記の要素をタブの切り替えで表示する
    ・各ダイアグラムの概要を示す
    ・要件定義として満たすべき事を示す
    (「8-2.検証のためのポイント」を参照)
    ・整合性のチェックを行いその結果を警告する
    (「8-3.整合性を高めるポイント」を参照)
end note
note as N2
    ＜ダイアグラム内容画面＞
    1段階目のタブで4つのステップを切り替える
    2段階目のタブで各ステップ内の各ダイアグラムの内容を切り替えて表示する
    □1段目　　　　　　　□2段目
    ・システム価格　　　　コンテキストモデル、非機能要求モデル
    ・システム外部環境　　業務モデル、利用シーンモデル、概念モデル
    ・システム境界　　　　ユースケースモデル、帳票モデル、イベントモデル、プロトコルモデル
    ・システム　　　　　　機能モデル、データモデル、ドメインモデル
end note
情報提供 .. N1
ダイアグラム表示 .. N2
@enduml