@startuml
title 図5-16 入出力情報を扱った画面帳票モデル
object ダイアグラム {
    名前
    ステレオタイプ
    ノート
}
object ダイアグラム内情報 {
    名前
    ステレオタイプ
    ノート
}
object ダイアグラム説明
object 要件定義検証ポイント {
    ダイアグラム名
    検証方法説明
}
object 整合性チェックポイント {
    整合性のポイント説明
    対応ダイアグラム名
    整合性をチェックする相手
}
note as N1
    ダイアグラムの種類に応じて
    繋がる先が異なるので
    表示するカラムが増減する
end note
note as N2
    ダイアグラムの種類に応じて
    その説明が関係している
end note
ダイアグラム o--"*" ダイアグラム内情報
ダイアグラム内情報 .. N1
ダイアグラム o-right- ダイアグラム説明
ダイアグラム説明 .. N2
要件定義検証ポイント -[hidden]- 整合性チェックポイント
@enduml